  DOCKER_REPOSITORY:     ghcr.io/dfe-digital/get-teacher-training-adviser-service
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Teacher Training Adviser Service
  PAAS_APPLICATION_NAME: get-teacher-training-adviser-service
  REVIEW_APPLICATION:    review-teacher-training-adviser
  SLACK_FAILURE:         '#ff0000'
  SLACK_SUCCESS:         '#00ff00'
  SLACK_ICON:            https://raw.githubusercontent.com//DFE-Digital/get-into-teaching-api/master/.github/image.png?size=48
  SLACK_USERNAME:        GiT Workflows
  SLACK_FOOTER:          Teacher Training Adviser Service

