inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - userresearch
    - production

Style/DateTime:
  Description: "Use Time over DateTime."
  StyleGuide: "#date--time"
  Enabled: false
  VersionAdded: "0.51"
  VersionChanged: "0.59"
  AllowCoercion: false

Style/ClassVars:
  Enabled: false
