inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - rolling
    - preprod
    - production

Style/DateTime:
  Description: "Use Time over DateTime."
  StyleGuide: "#date--time"
  Enabled: false
  VersionAdded: "0.51"
  VersionChanged: "0.59"
  AllowCoercion: false

Style/ClassVars:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Rails/SaveBang:
  Enabled: true
  Exclude:
    - spec/**/*

RSpec/StubbedMock:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
