default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: get_tta_service_dev

test:
  <<: *default
  database: get_tta_service_test<%= ENV['TEST_ENV_NUMBER'] %>
  host: localhost
  username: postgres
  password: postgres

production: &production
  <<: *default
  database: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "name") %>
  host: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "host") %>
  username: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "username") %>
  password: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "password") %>
  port: <%= Rails.application.config.x.vcap_services.dig("postgres", 0, "credentials", "port") %>

rolling:
  <<: *production

preprod:
  <<: *production

userresearch:
  <<: *production
