name: cve
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image Name to be Tested'
        required: true

env:
  APP_REPOSITORY:  dfedigital/get-teacher-training-adviser-service
  CONTAINER:       get-teacher-training-adviser-service
  DOMAIN:          london.cloudapps.digital

jobs:
  cve:
    name: 'CVE Test'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Scan image
        uses: anchore/scan-action@v2
        with:
             image: ${{github.event.inputs.image}}
             fail-build: true
             severity-cutoff: high
             acs-report-enable: true
           
      - name: upload Anchore scan SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_MESSAGE: 'Pipeline Failure carrying out CVE Testing on ${{ github.event.inputs.image }}'
           SLACK_TITLE: 'Failure: CVE Testing has failed'
