name: Run CVE scanner 
on:
  workflow_dispatch:

jobs:
  cve:
    name: CVE scanner 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: set-up-environment
        uses: DFE-Digital/github-actions/set-up-environment@master

      - name: Install Cloud Foundry
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf7-cli  
          
      - name: Login to Cloud Foundry
        run: cf login -a api.london.cloud.service.gov.uk -u ${{secrets.GOVUKPAAS_USERNAME}} -p ${{secrets.GOVUKPAAS_PASSWORD}} -s get-into-teaching-monitoring
             
      - name: Push App
        run: cf push STEVE --docker-image alpine --no-start
      
      - name: Set Env
        run: |
            cf set-env STEVE ACTIONS_API_ACCESS_TOKEN '${{secrets.ACTIONS_API_ACCESS_TOKEN}}'
            cf set-env STEVE DEV_ARM_ACCESS_KEY '${{secrets.DEV_ARM_ACCESS_KEY}}'
            cf set-env STEVE DOCKERHUB_PERSONAL_ACCESS_TOKEN '${{secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN}}'
            cf set-env STEVE DOCKERHUB_REPOSITORY '${{secrets.DOCKERHUB_REPOSITORY}}'
            cf set-env STEVE DOCKERHUB_USERNAME '${{secrets.DOCKERHUB_USERNAME}}'
            cf set-env STEVE GOVUKPAAS_PASSWORD '${{secrets.GOVUKPAAS_PASSWORD}}'
            cf set-env STEVE GOVUKPAAS_USERNAME '${{secrets.GOVUKPAAS_USERNAME}}'
            cf set-env STEVE HTTPAUTH_PASSWORD '${{secrets.HTTPAUTH_PASSWORD}}'
            cf set-env STEVE HTTPAUTH_USERNAME '${{secrets.HTTPAUTH_USERNAME}}'
            cf set-env STEVE PROD_ARM_ACCESS_KEY '${{secrets.PROD_ARM_ACCESS_KEY}}'
            cf set-env STEVE RAILS_MASTER_KEY_PREPROD '${{secrets.RAILS_MASTER_KEY_PREPROD}}'
            cf set-env STEVE RAILS_MASTER_KEY_PRODUCTION '${{secrets.RAILS_MASTER_KEY_PRODUCTION}}'
            cf set-env STEVE RAILS_MASTER_KEY_ROLLING '${{secrets.RAILS_MASTER_KEY_ROLLING}}'
            cf set-env STEVE SENTRY_DSN '${{secrets.SENTRY_DSN}}'
            cf set-env STEVE SLACK_RELEASE_NOTE_WEBHOOK '${{secrets.SLACK_RELEASE_NOTE_WEBHOOK}}'
            cf set-env STEVE SLACK_WEBHOOK '${{secrets.SLACK_WEBHOOK}}'
            cf set-env STEVE STATUS_CAKE_API '${{secrets.STATUS_CAKE_API}}'
            cf set-env STEVE TEST_ARM_ACCESS_KEY '${{secrets.TEST_ARM_ACCESS_KEY}}'
            cf set-env STEVE TRELLO_KEY '${{secrets.TRELLO_KEY}}'
            cf set-env STEVE TRELLO_TOKEN '${{secrets.TRELLO_TOKEN}}'
            cf set-env STEVE SONAR_TOKEN '${{secrets.SONAR_TOKEN}}'
              
      - name: Give me 2 minutes
        run:  sleep 120
        
      - name: Drop Image
        run:  cf delete STEVE -r -f
