name: Cypress
on:
  workflow_dispatch:

jobs:
  tests:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Trigger Cypress Testing
         uses: benc-uk/workflow-dispatch@v1.1
         with:
           repo:     DFE-Digital/get-into-teaching-frontend-tests
           workflow: Cypress
           token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
           inputs: '{"application": "TTA"}'
