name: Cypress
on:
  workflow_dispatch:
    inputs:
      sha:
        description: 'Commit sha to be deployed'
        required: true

jobs:
  tests:
    name: 'Run Cypress Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
             repository: DFE-Digital/get-into-teaching-frontend-tests

      - name: Trigger Cypress Tests
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          repo:  DFE-Digital/get-into-teaching-frontend-tests
          ref:   refs/heads/master
          workflow: Cypress
          token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
          inputs: '{"application": "TTA"}'
          
      - name: Wait for Cypress Tests
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build
        with:
          repo:  get-into-teaching-frontend-tests
          owner: DFE-Digital
          token: ${{ secrets.ACTIONS_API_ACCESS_TOKEN }}
          checkName: Run Cypress Tests
          ref:   refs/heads/master
          timeoutSeconds: 600

