name: Destroy Review Instance 
on:
  pull_request:
    types: [closed]

env:
  DOCKERHUB_REPOSITORY: dfedigital/get-teacher-training-adviser-service
  DOMAIN:               london.cloudapps.digital
  PROJECT:              Teacher Training Adviser Service
  REVIEW_APPLICATION:   review-teacher-training-adviser
  APPLICATION_NAME:     get-teacher-training-adviser-service

jobs:
  destroy:
    name: 'Destroy ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Setup Environment Variables
         id:  variables
         run: |
                 echo ::set-output name=ARM_ACCESS_KEY::$(echo "${{ secrets.DEV_ARM_ACCESS_KEY  }}" )
                 echo ::set-output name=pr_name::${{env.REVIEW_APPLICATION}}-${{github.event.number}}
                 echo ::set-output name=url::"https://${{env.REVIEW_APPLICATION}}-${{github.event.number}}.${{env.DOMAIN}}"
                 echo ::set-output name=RAILS_ENV::$(echo "rolling" )
                 echo ::set-output name=RAILS_MASTER_KEY::$(echo "${{ secrets.RAILS_MASTER_KEY_ROLLING }}" )
                 echo ::set-output name=HTTP_PASSWORD::$(echo "${{ secrets.HTTPAUTH_PASSWORD }}" )
                 echo ::set-output name=HTTP_USERNAME::$(echo "${{ secrets.HTTPAUTH_USERNAME }}" )
                 echo ::set-output name=control::$(echo "dev" )
                 echo ::set-output name=healthcheck::"${{env.REVIEW_APPLICATION}}-${{github.event.inputs.pr}}"

       - uses: hashicorp/setup-terraform@v1.2.1
         with:
              terraform_version: 0.13.4

       - name: Wait for any previous runs to complete
         uses: softprops/turnstyle@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           continue-after-seconds: 180

       - name: Terraform Destroy
         run: |
             cd terraform/paas && pwd
             terraform init -backend-config=review.bk.vars -backend-config="key=${{steps.variables.outputs.pr_name}}.tfstate"
             terraform destroy -var-file=review.env.tfvars -auto-approve
         env:
             ARM_ACCESS_KEY:           "${{ steps.variables.outputs.ARM_ACCESS_KEY  }}"
             TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME  }}"
             TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD  }}"
             TF_VAR_RAILS_ENV:         "${{ steps.variables.outputs.RAILS_ENV  }}"
             TF_VAR_RAILS_MASTER_KEY:  "${{ steps.variables.outputs.RAILS_MASTER_KEY  }}"
             TF_VAR_HTTPAUTH_PASSWORD: "${{ steps.variables.outputs.HTTP_PASSWORD  }}"
             TF_VAR_HTTPAUTH_USERNAME: "${{ steps.variables.outputs.HTTP_USERNAME  }}"
             TF_VAR_docker_username:   "${{ secrets.DOCKERHUB_USERNAME }}"
             TF_VAR_docker_password:   "${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}"

       - name: Slack Notification
         if: failure()
         uses: rtCamp/action-slack-notify@master
         env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#B90E0A'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_TITLE: 'Failure:  Closing Review'
           SLACK_MESSAGE: 'Failure with  Closing ${{env.PROJECT}} Review'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
