name: owasp
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to test to eg: dev/test/prod etc'
        required: true

env:
  DOCKERHUB_REPOSITORY:  dfedigital/get-teacher-training-adviser-service
  DOMAIN:                london.cloudapps.digital
  APPLICATION:           Teacher Training Adviser Service
  REVIEW_APPLICATION:    review-teacher-training-adviser
  PAAS_APPLICATION_NAME: get-teacher-training-adviser-service

jobs:
  owasp:
    name: 'OWASP Test ${{ github.event.inputs.environment }}'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://${{ secrets.HTTPAUTH_USERNAME }}:${{ secrets.HTTPAUTH_PASSWORD }}@${{env.PAAS_APPLICATION_NAME}}-${{ github.event.inputs.environment }}.${{env.DOMAIN}}/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'

      - name: Slack Notification
        if: failure()
        uses: rtCamp/action-slack-notify@master
        env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: 'Pipeline Failure carrying out OWASP Testing on https://${{env.PAAS_APPLICATION_NAME}}-${{ github.event.inputs.environment }}.${{env.DOMAIN}}/'
           SLACK_TITLE: 'Failure: OWSAP Testing has failed on ${{ github.event.inputs.environment }}'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
           SLACK_FOOTER: "${{env.APPLICATION}}"
