name: Pull Request 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.6
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1  
    - name: Install Yarn
      run: yarn install && yarn cache clean
    - name: Results Directory
      run: mkdir results
    - name: Install dependencies
      run: bundle install
    - name: Compile
      run: bundle exec rake assets:precompile
    - name: Run tests
      run:  RAILS_ENV=test bundle exec rspec --format RspecJunitFormatter --out results/xunit-result-rspec.xml
    - uses: actions/upload-artifact@v2
      if: always()
      with:
          name: test-results
          path: results/xunit-result-rspec.xml
    - name: Run sonarqube
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=dfe-digital
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=PP
           -Dsonar.simplecovrcov.reportPath=results
