name: Pull Request 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.6
    - name: Install Yarn
      run: yarn install && yarn cache clean
    - name: Install dependencies
      run: bundle install
    - name: Install Rspec Junit Formatter
      run: gem install rspec_junit_formatter
    - name: Compile
      run: bundle exec rake assets:precompile
    - name: Run tests
      run: bundle exec rspec --format RspecJunitFormatter --out rspec.xml
    - uses: actions/upload-artifact@v2
      with:
          name: test-results
          path: rspec.xml
