name: Pull Request 
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  test_docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint Dockerfile
      uses: brpaz/hadolint-action@master
      with:
        dockerfile: "Dockerfile"
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.6.6
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v1  
    - name: Install Yarn
      run: yarn install && yarn cache clean
    - name: Install dependencies
      run: bundle install
    - name: Compile
      run: bundle exec rake assets:precompile
    - name: Run tests
      run:  RAILS_ENV=test bundle exec rspec
    - uses: actions/upload-artifact@v2
      if: always()
      with:
          name: Test_Results
          path: out/
    - name: Run sonarqube
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: sonar-scanner
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
           -Dsonar.organization=dfe-digital
           -Dsonar.host.url=https://sonarcloud.io/
           -Dsonar.projectKey=PP
           -Dsonar.testExecutionReportPaths=out/test-report.xml
           -Dsonar.sources='spec,app,db,config'
