---  
name: Release to User Research (UR)
on: 
  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: dfedigital/get-teacher-training-adviser-service
  TF_VAR_RAILS_ENV:         "userresearch"

jobs:
  deploy_qa:
    name: 'Deploy to Quality Assurance'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
       - name: Checkout
         uses: actions/checkout@v2

       - name: Get Short SHA
         id: sha
         run: echo ::set-output name=short::$(git rev-parse --short $GITHUB_SHA)

       - uses: hashicorp/setup-terraform@v1
         with:
              terraform_version: 0.13.4

       - name: Wait for any previous runs to complete
         uses: softprops/turnstyle@v1
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           continue-after-seconds: 180

       - name: Terraform Init
         run: |
             cd terraform/paas && pwd
             terraform init -backend-config=ur.bk.vars
         env:
              TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME  }}"
              TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD  }}"
              ARM_ACCESS_KEY:           "${{ secrets.TEST_ARM_ACCESS_KEY  }}"

       - name: Terraform Plan
         run: |
             cd terraform/paas && pwd
             terraform plan -var-file=ur.env.tfvars -out plan
         env:
              TF_VAR_paas_adviser_docker_image: ${{env.DOCKERHUB_REPOSITORY}}:sha-${{ steps.sha.outputs.short}} 
              TF_VAR_HTTPAUTH_PASSWORD: "${{ secrets.UR_HTTPAUTH_PASSWORD  }}"
              TF_VAR_HTTPAUTH_USERNAME: "${{ secrets.UR_HTTPAUTH_USERNAME  }}"
              TF_VAR_RAILS_MASTER_KEY:  "${{ secrets.RAILS_MASTER_KEY_USERRESEARCH}}"
              TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME  }}"
              TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD  }}"
              ARM_ACCESS_KEY:           "${{ secrets.TEST_ARM_ACCESS_KEY  }}"

       - name: Terraform Apply
         run: |
             cd terraform/paas && pwd
             terraform apply -auto-approve plan
         env:
              TF_VAR_user:              "${{ secrets.GOVUKPAAS_USERNAME  }}"
              TF_VAR_password:          "${{ secrets.GOVUKPAAS_PASSWORD  }}"
              ARM_ACCESS_KEY:           "${{ secrets.TEST_ARM_ACCESS_KEY  }}"

       - name: Smoke tests
         run: |
             tests/confidence/healthcheck.sh  "get-teacher-training-adviser-service-ur"  "${{ steps.sha.outputs.short }}"
         env:
             HTTPAUTH_PASSWORD: "${{ secrets.UR_HTTPAUTH_PASSWORD }}"
             HTTPAUTH_USERNAME: "${{ secrets.UR_HTTPAUTH_USERNAME }}"
   
       - name: Create Sentry release
         if: success()
         uses: getsentry/action-release@v1.1.1
         env:
           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
           SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
           SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
         with:
           environment: ur
           
       - name: Slack Notification
         if: failure()
         uses: rtCamp/action-slack-notify@master
         env:
           SLACK_CHANNEL: getintoteaching_tech
           SLACK_COLOR: '#3278BD'
           SLACK_ICON: https://github.com/rtCamp.png?size=48
           SLACK_MESSAGE: ':disappointed_relieved: Pipeline Failure carrying out job ${{github.job}} :disappointed_relieved:'
           SLACK_TITLE: 'Failure: ${{ github.workflow }}'
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
